name: texno_bozor
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'



dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^4.2.2
  flutter_native_splash: ^2.3.1
  change_app_package_name: ^1.1.0
  curved_navigation_bar: ^1.0.3
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^15.1.0+1
  firebase_auth: ^4.7.1
  firebase_storage: ^11.2.5
  cached_network_image: ^3.2.3
  google_sign_in: ^6.1.4
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  zoom_tap_animation: ^1.1.0
  image_picker: ^1.0.1
  provider: ^6.0.5
  sqflite: ^2.3.0
  dio: ^5.3.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-BlackItalic.ttf
        - asset: assets/fonts/DMSans-Black.ttf
        - asset: assets/fonts/DMSans-Bold.ttf
        - asset: assets/fonts/DMSans-BoldItalic.ttf
        - asset: assets/fonts/DMSans-ExtraBold.ttf
        - asset: assets/fonts/DMSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/DMSans-ExtraLight.ttf
        - asset: assets/fonts/DMSans-ExtraLightItalic.ttf
        - asset: assets/fonts/DMSans-Italic.ttf
        - asset: assets/fonts/DMSans-Light.ttf
        - asset: assets/fonts/DMSans-LightItalic.ttf
        - asset: assets/fonts/DMSans-Medium.ttf
        - asset: assets/fonts/DMSans-MediumItalic.ttf
        - asset: assets/fonts/DMSans-SemiBold.ttf
        - asset: assets/fonts/DMSans-SemiBold.ttf
        - asset: assets/fonts/DMSans-Thin.ttf
        - asset: assets/fonts/DMSans-ThinItalic.ttf

flutter_native_splash:
  color: "#ffffff"
  background_image: assets/icons/logo.png
  branding: assets/icons/logo.png
  color_dark: "#121212"
  image_dark: assets/icons/logo.png
  branding_dark: assets/icons/logo.png

  android_12:
    image: assets/icons/logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/icons/logo.png
    icon_background_color_dark: "#121212"

  web: false